apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: itsmesimha/frontend-nginx:29
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_SERVICE_HOST
          value: backend-service
        - name: BACKEND_SERVICE_PORT
          value: "5000"
