apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: itsmesimha/frontend-nginx:32
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_SERVICE_HOST
          value: backend-service
        - name: BACKEND_SERVICE_PORT
          value: "5000"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf  # Ensure it maps correctly
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config  # Make sure this ConfigMap exists
