apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: web-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: itsmesimha/frontend-nginx:16
        ports:
        - containerPort: 80
