apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-tier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: flask-app
        image: itsmesimha/backend-flask:11
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "your-rds-endpoint.amazonaws.com"
        - name: MYSQL_USER
          value: "your-db-username"
        - name: MYSQL_PASSWORD
          value: "your-db-password"
        - name: MYSQL_DB
          value: "health-care-db"
