apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: flask-app
        image: itsmesimha/backend-flask:32
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "database-1.cgkf5qiqs0zz.us-east-2.rds.amazonaws.com"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "admin1234"
        - name: MYSQL_DB
          value: "database-1"
